package bot.services

import bot.models.*
import org.jsoup.nodes.Document
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service

import static bot.utilities.Browser.*

@Service
class Bible {

    @Value('${bot.url.bible}')
    private String url

    String getVerse() {
        Document doc = getHTML(url)
        String text = doc.select(".bibleVerse").first().ownText()
        String verse = doc.select(".bibleChapter a").first().text()
        return String.format("%s - *%s*", text, verse)
    }

    List<Food> searchForFoods(String food) {

        def foods = []

        for (String f : cleanFoods) {
            if (match(f, food)) {
                foods.add(new Food(name: f, clean: true))
            }
        }

        for (String f : dirtyFoods) {
            if (match(f, food)) {
                foods.add(new Food(name: f, clean: false))
            }
        }

        return foods
    }

    private static boolean match(String foodName, String searchTerm) {
        def words = foodName.toUpperCase().split(" ")

        for (String word in words) {
            if (searchTerm.equalsIgnoreCase(word)) {
                return true
            }
        }

        return false
    }

    private def cleanFoods = [
            'Cricket',
            'Grasshopper',
            'Katydid',
            'Locust',
            'Antelope',
            'Bison',
            'Buffalo',
            'Caribou',
            'Cattle',
            'Beef',
            'Veal',
            'Deer',
            'Reindeer',
            'Gazelle',
            'Giraffe',
            'Goat',
            'Hart',
            'Ibex',
            'Lamb',
            'Sheep',
            'Hogget',
            'Mutton',
            'Moose',
            'Ox',
            'Cow',
            'Roebuck',
            'Sheep',
            'Addax',
            'Big Horn Sheep',
            'Blackbuck',
            'Blesbok',
            'Bongo',
            'Buffalo',
            'Bushbuck',
            'Caribou',
            'Dik Dik',
            'Eland',
            'Elk',
            'Gazelle',
            'Gemsbok',
            'Gerenuk',
            'Goral',
            'Hartebeest',
            'Hirola',
            'Impala',
            'Kafue Lachwe',
            'Kafue Lechwe',
            'Kudu',
            'Klipspringer',
            'Markhor',
            'Moose',
            'Mule Deer',
            'Muntjac',
            'Musk Ox   ',
            'Nilgai',
            'Nyala',
            'Okapi',
            'Oribi',
            'Oryx',
            'Pronghorn',
            'Reedbuck',
            'Sable',
            'Sitatunga',
            'Springbuck ',
            'Springbok ',
            'Steenbok',
            'Takin',
            'Topi',
            'Tsessebe',
            'Urial',
            'Waterbuck',
            'White Tail Deer',
            'Wildebeest',
            'Yak',
            'Albacore',
            'Crevalle',
            'Horse Mackerel',
            'Jack',
            'Alewives',
            'Branch Herring',
            'River Herring',
            'Klippers',
            'Anchovies',
            'Black Drum',
            'Bluebacks',
            'Glut Herrings',
            'Bluebill Sunfish',
            'Bluefish',
            'Blue Runner',
            'Hardtail',
            'Bonitos',
            'Boston Bluefish',
            'Pollock',
            'Bowfin',
            'Buffalofish',
            'Butterfish',
            'Carp',
            'Chubs',
            'Bloater',
            'Longjaw',
            'Blackfin',
            'Cod',
            'Common Sucker',
            'Fresh Water Mullet',
            'White Sucker',
            'Crappies',
            'Black Crappies',
            'White Crappies',
            'Flounder',
            'Dab',
            'Gray Sole',
            'Lemon Sole',
            'Summer Flounder',
            'Winter Flounder',
            'Yellow Tail',
            'Frost Fish',
            'Ice Fish',
            'Smelt',
            'Groupers',
            'Black Grouper',
            'Gag',
            'Nassau Grouper',
            'Red Grouper',
            'Yellowfish Grouper',
            'Grunts',
            'White Grunts',
            'Yellow Grunts',
            'Gulf Pike',
            'Robalo',
            'Snook',
            'Sergeant',
            'Haddock',
            'Hake',
            'Halibut',
            'Herring',
            'Kippers',
            'Lake Herring',
            'Sea Herring',
            'Kingfish',
            'Long Nose Sucker',
            'Northern Sucker',
            'Red Striped Sucker',
            'Mackerel',
            'Jack Mackerel',
            'Menhaden',
            'Mullet',
            'Muskeilunge',
            'Jacks',
            'Pickerels',
            'Pig Fish',
            'Pikes',
            'Pompano',
            'Porgy',
            'Scup',
            'Red Drum',
            'Redfish',
            'Red Horse Sucker',
            'Redfin',
            'Red Snapper',
            'Salmon',
            'Chum',
            'Coho',
            'King',
            'Pink',
            'Red',
            'Bonefish',
            'Sardine',
            'Pilchards',
            'Sea Bass',
            'Shad',
            'Sheepshead',
            'Silver Hake',
            'Whiting',
            'Silversides',
            'Spanish Mackerel',
            'Striped Bass',
            'Trouts',
            'Tilapia',
            'Snapper',
            'Tarpon Fish',
            'Gray Sea Trouts',
            'Weakfish',
            'Lake Trout',
            'Sand Sea Trout',
            'White Sea Trout',
            'Spotted SeaTrout',
            'Tunas',
            'Bluefin',
            'Yellowfin',
            'Skipjack',
            'White Fish',
            'Perch',
            'Yellow Perch',
            'Chicken',
            'Dove',
            'Duck',
            'Goose',
            'Grouse',
            'Guinea Fowl',
            'Partridge',
            'Peafowl',
            'Pheasant',
            'Pigeon',
            'Prairie Chicken',
            'Ptarmigan',
            'Quail',
            'Sagehen',
            'Sparrow',
            'Teal',
            'Turkey'
    ]

    private def dirtyFoods = [
            'Pig',
            'Butterfly',
            'Ambush Bug',
            'Ant',
            'Aphid',
            'Armyworm',
            'Assassin Bug',
            'Atlas Moth',
            'Backswimmer',
            'Bedbug',
            'Bee',
            'Beetle',
            'Bluet',
            'Borer',
            'Bug',
            'Bumblebee',
            'Butterfly',
            'Carpenter Ant',
            'Caterpillar',
            'Cicada',
            'Cockroach',
            'Crane Fly',
            'Cutworm',
            'Damselfly',
            'Darkling Beetle',
            'Dragonfly',
            'Dung Beetle',
            'Earwig',
            'Fire Ant',
            'Firefly',
            'Flea',
            'Fruitfly',
            'Gnat',
            'Ground Beetle',
            'Gypsy Moth',
            'Harlequin Bug',
            'Horse Fly',
            'Honeybee',
            'Hornet',
            'House Fly',
            'Hover Fly',
            'Japanese Beetle',
            'Jumping Bean',
            'Junebug',
            'Kissing Bug',
            'Ladybug',
            'Lacewing',
            'Leafcutter Ant',
            'Leafhopper',
            'Lice',
            'Lightning Bug',
            'Longhorn Beetle',
            'Louse',
            'Luna Moth',
            'Maggot',
            'Mayfly',
            'Meadowhawk',
            'Mealworm',
            'Metamorphosis',
            'Midge',
            'Milkweed Bug',
            'Monarch',
            'Morpho',
            'Mosquito',
            'Moth',
            'Nymph',
            'Owl Butterfly',
            'Paper Wasp',
            'Planthopper',
            'Pond Skater',
            'Praying Mantid',
            'Praying Mantis',
            'Robber Fly',
            'Scarab',
            'Silkworm',
            'Silverfish',
            'Skipper',
            'Spittlebug',
            'Springtail',
            'Stag Beetle',
            'Stink Bug',
            'Stonefly',
            'Termite',
            'Centipede',
            'Scorpion',
            'Skink',
            'Thrip',
            'Chameleon',
            'Tiger Beetle',
            'Tiger Moth',
            'Tsetse Fly',
            'Walkingstick',
            'Wasp',
            'Water Boatman',
            'Waterbug',
            'Waterstrider',
            'Weevil',
            'Woodborer',
            'Yellowjacket',
            'Albatross',
            'Bittern',
            'Buzzard',
            'Condor',
            'Coot',
            'Cormorant',
            'Crane',
            'Crow',
            'Cuckoo',
            'Eagle',
            'Falcon',
            'Peacock',
            'Flamingo Grebe',
            'Grosbeak',
            'Gull',
            'Hadida',
            'Hawk',
            'Heron',
            'Ibis',
            'Kite',
            'Kingfisher',
            'Lapwing',
            'Nighthawk',
            'Loon',
            'Magpie',
            'Osprey',
            'Ossifrage',
            'Ostrich',
            'Owl',
            'Parrot',
            'Pelican',
            'Penguin',
            'Plover',
            'Rail',
            'Raven',
            'Hoopoe',
            'Roadrunner',
            'Sandpiper',
            'Seagull',
            'Stork',
            'Swallow',
            'Swift',
            'Swan',
            'Vulture',
            'Black vulture',
            'Water hen',
            'Woodpecker',
            'Abalone',
            'Bullhead',
            'Catfish',
            'Clams',
            'Conch',
            'Crabs',
            'Crayfish',
            'Crawfish',
            'Crawdad',
            'Cuttlefish',
            'Dolphin',
            'Otter',
            'Eel',
            'Jellyfish',
            'Limpet',
            'Lobster',
            'Marlin',
            'Mussel',
            'Octopus',
            'Oysters',
            'Paddlefish',
            'Porpoise',
            'Scallop',
            'Seal',
            'Shark',
            'Shrimp',
            'Snail',
            'Squid',
            'Calamari',
            'Stickleback',
            'Sturgeon',
            'Swordfish',
            'Walrus',
            'Whale',
            'Alligator',
            'Alpaca',
            'Llama',
            'Armadillo',
            'Ass',
            'Badger',
            'Bat',
            'Bear',
            'Panda',
            'Beaver',
            'Caiman',
            'Camel',
            'Cats',
            'Cheetah',
            'Cougar',
            'Jaguar',
            'Leopard',
            'Lion',
            'Puma',
            'Panther',
            'Tiger',
            'Crocodile',
            'Dogs',
            'Coyote',
            'Fox',
            'Hyena',
            'Jackal',
            'Wolf',
            'Elephant',
            'Frog',
            'Gorilla',
            'Groundhog',
            'Guinea Pig',
            'Hippopotamus',
            'Horse',
            'Donkey',
            'Mule',
            'Onager',
            'Zebra',
            'Madora',
            'Mopane worm',
            'Earthworm',
            'Shrew',
            'Kangaroo',
            'Koala',
            'Echidna',
            'Llama',
            'Lizards',
            'Mice',
            'Mole',
            'Monkey',
            'Baboon',
            'Chimpanzee',
            'Muskrat',
            'Newt',
            'Porcupine',
            'Possum',
            'Rabbit',
            'Hyrax',
            'Raccoon',
            'Rats',
            'Coney',
            'Rhinoceros',
            'Salamander',
            'Skunk',
            'Snake',
            'Spider',
            'Squirrel',
            'Swine',
            'Boar',
            'Hog',
            'Warthog',
            'Peccary',
            'Platypus',
            'Bacon',
            'Pork',
            'Pork sausage',
            'Pangolin',
            'Ham',
            'Pig Lard',
            'Toad',
            'Turtle',
            'Ferret',
            'Mouse',
            'Stoat',
            'Vampire',
            'Wallaby',
            'Weasel',
            'Werewolf',
            'Dragon',
            'Wolverine'
    ]
}